# Generated by Django 4.2.21 on 2025-05-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Pessoa',
        ),
    ]
